version: "3.8"
services:
  server:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mysqldb
  mysqldb:
    image: "mysql:8.0.32"
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: gymdb
      MYSQL_USER: gymuser
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: 123456
