spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shashank
    username: ENC(sodr1UwOY627a+ad24O17w==)
    password: ENC(Q6NiYHDpcZhOMV1nOY7whVR85uI9zPf7)
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
  mvc:
    contentnegotiation:
      defaultContentType: application/json
  mail:
    host: smtp.gmail.com
    port: 587
    username: ENC(HWpdG5Z27E1DqsHNd6V17ZP+1MTjwmJuFLOqkFw1/nXHe0/LdzjzjQ==)
    password: ENC(TJUS+b+JA4s629OtnLnGOyYWTlgh8h5YpAmbWru7QbM=)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    cache:
      type: redis
      redis:
        cache-null-values: true
logging:
  level:
    org:
      springframework: INFO
  file: app.log
user:
  maxplans: 6
server:
  port : 8081
